### ISSUE TITLE
Why never enough candles?

### ISSUE THREAD

**Issue by Reapor-Yurnero** [Tiyth/Minecraft-Guides-Thaumcraft6#1]
In chapter Infusion Stabilization Stable Infusion, it is said there's never enough candles. However, in chapter Advanced Foci / Basic Infusion, it is said "More than a total of 12 “occult” items will cause instability". There's a trivial contradiction.

**Comment by luihumberto** [comment]
Sorry for bumping, but for safety I will just put 3 candles on a square.
